// Auto-generated from admin DB at 2026-06-09T13:23:35
window.YEDAO_DATA = {
  "ARCHETYPES": [
    {
      "id": "violence",
      "vol": 1,
      "name": "Violence",
      "cn": "暴力",
      "tone": "violence",
      "summary": "Dark medieval fantasy distilled into a single knight. Armor forged from nightmares.",
      "cn_summary": "中世纪暗黑奇幻凝缩为一位骑士。盔甲由噩梦铸成。",
      "sref": "1738250716 3115425663",
      "prompt": "a medieval knight in obsidian armor, fog, ash, --ar 16:9 --sref 1738250716 3115425663 --stylize 800 --v 7",
      "use": "战争场面 · 末世题材 · 暗黑奇幻 · 戏剧化光影",
      "palette": [
        "#0a0506",
        "#2a0a0a",
        "#5a1a1a",
        "#9a3a3a",
        "#d4af37"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "magenta",
      "vol": 1,
      "name": "Magenta",
      "cn": "洋红",
      "tone": "magenta",
      "summary": "Opulent decay. Roman arenas and crusader fields drenched in deep magenta and iron.",
      "cn_summary": "奢靡的衰败。罗马竞技场与十字军战场浸满深洋红与铁锈。",
      "sref": "1847423642 3589989023",
      "prompt": "coliseum at dusk, magenta floodlights, iron gates, --ar 16:9 --sref 1847423642 3589989023 --v 7",
      "use": "古罗马 · 颓废史诗 · 衰败贵族 · 戏剧性场景",
      "palette": [
        "#1a0612",
        "#3a0a2a",
        "#7a1a4a",
        "#c43a7a",
        "#e8b8d4"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "angels",
      "vol": 1,
      "name": "Angels",
      "cn": "天使",
      "tone": "angels",
      "summary": "Ethereal beings caught between light and shadow. Celestial forms rendered with reverence.",
      "cn_summary": "游离于光影之间的飘渺存在。天界形体以敬畏之心呈现。",
      "sref": "497106809 1258733889",
      "prompt": "a seraph with six wings, soft volumetric light, --ar 16:9 --sref 497106809 1258733889 --v 7",
      "use": "宗教画 · 神性题材 · 文艺复兴 · 神圣场景",
      "palette": [
        "#0a0a14",
        "#1a1a3a",
        "#3a3a6a",
        "#b0b0d4",
        "#f0e8c8"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "golden-leaf",
      "vol": 1,
      "name": "Golden Leaf",
      "cn": "金叶",
      "tone": "golden-leaf",
      "summary": "Forests of liquid gold and diamond landscapes. Nature reimagined through precious metallurgy.",
      "cn_summary": "液态金与钻石地貌构成的森林。自然被贵金属冶金学重新想象。",
      "sref": "117504652 2300450134",
      "prompt": "a forest of liquid gold trees, diamond river, --ar 16:9 --sref 117504652 2300450134 --v 7",
      "use": "奢华自然 · 巴洛克 · 神话 · 装饰性强",
      "palette": [
        "#1a1408",
        "#3a2a10",
        "#7a5a1a",
        "#d4a830",
        "#fff0a0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "miramis",
      "vol": 1,
      "name": "Miramis",
      "cn": "米拉米斯",
      "tone": "miramis",
      "summary": "A dreamlike civilization of white horses, floating lanterns, and forests shrouded in mist.",
      "cn_summary": "白马、浮灯、薄雾森林构成的梦境文明。柔软、古老、永恒。",
      "sref": "497106809 1258733889",
      "prompt": "a white horse on a misty ridge, paper lanterns rising, --ar 16:9 --sref 497106809 1258733889 --v 7",
      "use": "梦境 · 仙侠 · 古风 · 治愈系",
      "palette": [
        "#0a1418",
        "#1a3038",
        "#3a5868",
        "#8aaab8",
        "#e8e0d4"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "mandala",
      "vol": 1,
      "name": "Mandala",
      "cn": "曼陀罗",
      "tone": "mandala",
      "summary": "Sacred geometry meets generative art. Intricate, meditative patterns that reveal themselves slowly.",
      "cn_summary": "神圣几何遇上生成艺术。错综、冥想式的图案，看得越久越显现。",
      "sref": "202022303 2421432340",
      "prompt": "sacred mandala, intricate generative pattern, --ar 9:16 --sref 202022303 2421432340 --v 7",
      "use": "冥想 · 抽象 · 装饰艺术 · 视觉中心",
      "palette": [
        "#0a0612",
        "#1a0a2a",
        "#3a1a5a",
        "#7a3a9a",
        "#e0a8f0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "arcadia",
      "vol": 1,
      "name": "Arcadia",
      "cn": "阿卡迪亚",
      "tone": "arcadia",
      "summary": "Utopian landscapes bathed in warm light. An idealized pastoral vision where nature and civilization coexist.",
      "cn_summary": "沐浴在暖光中的乌托邦风景。理想化的田园图景，自然与文明共存。",
      "sref": "1847423642 3589989023 727063",
      "prompt": "pastoral idyll, golden hour, shepherds, marble temple, --ar 16:9 --sref 1847423642 3589989023 727063 --v 7",
      "use": "田园牧歌 · 古典神话 · 暖色广告 · 治愈系",
      "palette": [
        "#1a1408",
        "#3a2a18",
        "#7a5a3a",
        "#c89868",
        "#f0d8a0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "reykjavik",
      "vol": 1,
      "name": "Reykjavik",
      "cn": "雷克雅未克",
      "tone": "reykjavik",
      "summary": "Northern European street photography filtered through a Midjourney lens. Cold, grey, brutally honest.",
      "cn_summary": "北欧街头摄影经 Midjourney 镜头过滤。冷峻、灰调、残忍诚实。",
      "sref": "4079625911 145",
      "prompt": "berlin street photography, overcast, brutalist, --ar 5:6 --sref 4079625911 145 --v 7",
      "use": "街头摄影 · 城市纪实 · 冷淡风 · 极简编辑",
      "palette": [
        "#0a0c0e",
        "#1a1f24",
        "#3a444c",
        "#6a7480",
        "#a0a8b0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "romanticism",
      "vol": 1,
      "name": "Romanticism",
      "cn": "浪漫主义",
      "tone": "mandala",
      "summary": "Romantic, gothic, dreamlike. The architecture of an impossible cathedral city.",
      "cn_summary": "浪漫、哥特、梦呓。一座不可能存在的大教堂城市的建筑学。",
      "sref": "202022303 2421432340",
      "prompt": "an impossible cathedral city, fog, gargoyles, --ar 16:9 --sref 202022303 2421432340 --v 7",
      "use": "哥特建筑 · 浪漫主义 · 梦境城市 · 油画感",
      "palette": [
        "#0a0608",
        "#1a0a14",
        "#3a1a2a",
        "#7a3a5a",
        "#c898b0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "vapor",
      "vol": 1,
      "name": "Vapor",
      "cn": "蒸汽",
      "tone": "cyberpunk",
      "summary": "Hyper-saturated visions of a future that never was — pure neon and procedural light.",
      "cn_summary": "一个从未存在过的未来的过饱和幻象——纯粹的霓虹与程序化光。",
      "sref": "8036686603",
      "prompt": "vaporwave dreamscape, neon grid, magenta sun, --ar 16:9 --sref 8036686603 --v 7",
      "use": "复古未来 · 蒸汽波 · 封面设计 · 海报",
      "palette": [
        "#0a0a14",
        "#1a0a3a",
        "#3a1a7a",
        "#7a3aff",
        "#ff60c0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "decadence",
      "vol": 2,
      "name": "Decadence",
      "cn": "颓废",
      "tone": "decadence",
      "summary": "Wasteful luxury from a society past its peak. Crumbling castles, overripe fruit, fading grandeur.",
      "cn_summary": "一个走过巅峰的社会所留下的奢靡。坍塌的城堡、过熟的水果、褪色的辉煌。",
      "sref": "5111501329",
      "prompt": "crumbling baroque castle, overripe fruit on silver tray, --ar 16:9 --sref 5111501329 --v 7",
      "use": "颓废美学 · 巴洛克 · 衰败贵族 · 室内装饰",
      "palette": [
        "#1a0e08",
        "#2a1a10",
        "#5a3a24",
        "#a87a4a",
        "#e8c890"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "kids",
      "vol": 2,
      "name": "The Kids Are Alright",
      "cn": "少年们没事",
      "tone": "kids",
      "summary": "iPhone memories of youth culture at its peak. Cyborgs in hoodies, castle rooftops, neon generation.",
      "cn_summary": "青年文化巅峰期的 iPhone 记忆。连帽衫里的赛博格、城堡屋顶、霓虹世代。",
      "sref": "5892927696",
      "prompt": "teen cyborg in hoodie on castle rooftop at dusk, --ar 2:3 --sref 5892927696 --v 7",
      "use": "青年文化 · Y2K 复古 · 街头潮流 · 杂志封面",
      "palette": [
        "#0a0612",
        "#1a0a2a",
        "#3a1a5a",
        "#6a4a8a",
        "#e8a0d4"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "clockwork",
      "vol": 2,
      "name": "Clockwork Orange",
      "cn": "发条橙",
      "tone": "clockwork",
      "summary": "Brushwork that compresses meaning without detail. Raw, violent abstraction — every frame a punch.",
      "cn_summary": "压缩意义、放弃细节的笔触。原始、暴力的抽象——每一帧都是一拳。",
      "sref": "4635134509",
      "prompt": "a punch in ultra close-up, raw brushwork, --ar 2:3 --sref 4635134509 --v 7",
      "use": "暴力题材 · 抽象 · 戏剧化 · 编辑性强",
      "palette": [
        "#0a0a0a",
        "#2a0a0a",
        "#6a2a0a",
        "#c4601a",
        "#f0d040"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "california",
      "vol": 2,
      "name": "California",
      "cn": "加州",
      "tone": "california",
      "summary": "The beauty and the horror beneath the manicured surface. Sunlit facades hiding something darker.",
      "cn_summary": "精心修剪的表面之下的美与恐怖。阳光照亮的外立面背后，藏着更暗的东西。",
      "sref": "5111501329",
      "prompt": "california suburban house, manicured lawn, eerie undertone, --ar 3:2 --v 7",
      "use": "美国郊区 · 阳光下的不安 · 广告式构图",
      "palette": [
        "#1a0e08",
        "#3a1a0a",
        "#7a3a1a",
        "#d4842a",
        "#fce8a0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "afterglow",
      "vol": 2,
      "name": "Afterglow",
      "cn": "余晖",
      "tone": "afterglow",
      "summary": "Negative space as active silence. The fog that deletes the horizon, leaving only atmosphere.",
      "cn_summary": "作为\"主动静默\"的负空间。把地平线抹去的雾，只留下氛围。",
      "sref": "5111501329",
      "prompt": "a figure in dense fog, horizon deleted, --ar 3:2 --v 7",
      "use": "极简 · 留白 · 电影感 · 海报",
      "palette": [
        "#0a0c10",
        "#1a2228",
        "#3a444c",
        "#6a7884",
        "#a8b4be"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "harvest",
      "vol": 2,
      "name": "Harvest",
      "cn": "丰收",
      "tone": "harvest",
      "summary": "Matters of small concern. The details that hold everything together — horse carriages, door knobs, quiet light.",
      "cn_summary": "一些看似微小的事。马车、门把手、静谧的光——这些把一切兜住的细节。",
      "sref": "5111501329",
      "prompt": "closeup of an antique door knob in late afternoon light, --ar 16:9 --sref 5111501329 --v 7",
      "use": "静物 · 局部特写 · 怀旧 · 暖色系",
      "palette": [
        "#1a0e08",
        "#2a1a10",
        "#5a3a24",
        "#a87a4a",
        "#e8c890"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "synesthesia",
      "vol": 2,
      "name": "Synesthesia",
      "cn": "通感",
      "tone": "synesthesia",
      "summary": "Engineered sensory overload. Baking reality out of pure light — 5G towers, neon cookies, impossible color.",
      "cn_summary": "被设计出来的感官过载。用纯粹的光烘焙现实——5G 塔、霓虹饼干、不可思议的颜色。",
      "sref": "8259246301 5921189345",
      "prompt": "5G tower at sunset, neon chromatic aberration, --ar 3:2 --sref 8259246301 5921189345 --v 7",
      "use": "故障艺术 · 赛博 · 海报 · 唱片封面",
      "palette": [
        "#0a0a1a",
        "#2a0a4a",
        "#6a1a9a",
        "#e83aa0",
        "#60f0e0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "tetsuo",
      "vol": 2,
      "name": "Tetsuo",
      "cn": "铁雄",
      "tone": "tetsuo",
      "summary": "The big event. An impact so mighty everything lives around it — galaxies, suburbs, Akira's aftermath.",
      "cn_summary": "那场大事件。一次足以改写一切的巨大冲击——星系、市郊、AKIRA 的余波。",
      "sref": "5145412347",
      "prompt": "akira bike explosion, galaxy backdrop, --ar 3:2 --sref 5145412347 --v 7",
      "use": "末日 · 爆炸 · 冲击 · 漫画感",
      "palette": [
        "#0a0a1a",
        "#1a1a3a",
        "#5a3a1a",
        "#d4602a",
        "#fce848"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "shogo",
      "vol": 2,
      "name": "Shogo",
      "cn": "将吾",
      "tone": "shogo",
      "summary": "Every frame a painting. The art director's library made visual — robots, plush toys, ink-dark water.",
      "cn_summary": "每一帧都是一幅画。艺术指导的私人图书馆被可视化——机器人、毛绒玩具、墨黑的水。",
      "sref": "8259246301",
      "prompt": "plush robot toy in ink-black water, art directed, --ar 3:2 --sref 8259246301 --v 7",
      "use": "美术指导 · 玩具设计 · 静物 · 黑白",
      "palette": [
        "#0a0a0a",
        "#1a1a1a",
        "#3a3a3a",
        "#7a7a7a",
        "#e8e8e8"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "doppelganger",
      "vol": 2,
      "name": "Doppelganger",
      "cn": "分身",
      "tone": "doppelganger",
      "summary": "A trip to many worlds. Reality as a prism of refractions — wolves, spectacles, alternate selves.",
      "cn_summary": "穿越多重世界。现实作为折射的棱镜——狼群、镜框、平行的自我。",
      "sref": "80537067",
      "prompt": "spectacles refracting a wolf pack into multiple selves, --ar 16:9 --sref 80537067 --v 7",
      "use": "心理 · 平行宇宙 · 镜面 · 概念艺术",
      "palette": [
        "#0a0a14",
        "#2a0a3a",
        "#5a1a6a",
        "#8a3a9a",
        "#c8a8e0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "cyberpunk",
      "vol": 3,
      "name": "Cyberpunk",
      "cn": "赛博朋克",
      "tone": "cyberpunk",
      "summary": "Neon dystopia. Chrome meets flesh. Welcome to the Black Sun.",
      "cn_summary": "霓虹反乌托邦。铬合金撞上血肉。欢迎来到\"黑太阳\"。",
      "sref": "8036686603",
      "prompt": "cyberpunk alley at night, neon, rain, chrome cyborg, --ar 16:9 --sref 8036686603 --v 7",
      "use": "赛博朋克 · 城市夜景 · 角色设计 · 电影感",
      "palette": [
        "#0a0612",
        "#2a0a4a",
        "#7a1a8a",
        "#ff40a0",
        "#40f0ff"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "electroma",
      "vol": 3,
      "name": "Electroma",
      "cn": "电幻",
      "tone": "electroma",
      "summary": "The poetry of electric beasts. Signal, noise, lightning mid-discharge.",
      "cn_summary": "电兽的诗学。信号、噪声、正在放电的闪电。",
      "sref": "5892927696",
      "prompt": "lightning mid-discharge, electrical arc, motion blur, --ar 3:2 --sref 5892927696 --v 7",
      "use": "能量 · 电流 · 动感 · 海报",
      "palette": [
        "#0a1a2a",
        "#1a3a5a",
        "#3a6a8a",
        "#40a0d4",
        "#a0e8f0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "glass-candy",
      "vol": 3,
      "name": "Glass Candy",
      "cn": "玻璃糖",
      "tone": "glass-candy",
      "summary": "Product photography past the edge of reality. An impossible candy.",
      "cn_summary": "越过现实边缘的产品摄影。一颗不可能存在的糖。",
      "sref": "6210443140",
      "prompt": "iridescent glass candy on plinth, studio lighting, --ar 3:2 --sref 6210443140 --v 7",
      "use": "产品摄影 · 美妆 · 静物 · 商业插画",
      "palette": [
        "#2a1a3a",
        "#5a2a6a",
        "#a04a9a",
        "#e88ac8",
        "#fff0f8"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "vitruvian",
      "vol": 3,
      "name": "Vitruvian",
      "cn": "维特鲁威",
      "tone": "vitruvian",
      "summary": "Classical proportions. Da Vinci's grid as quantum information.",
      "cn_summary": "古典比例。达·芬奇的网格作为量子信息。",
      "sref": "117504652",
      "prompt": "vitruvian man rendered in quantum pixels, --ar 16:9 --sref 117504652 --v 7",
      "use": "古典 · 解剖 · 知识图像 · 概念",
      "palette": [
        "#0a0a0a",
        "#2a2010",
        "#6a5830",
        "#c8a850",
        "#f0e0a0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "dreamcore",
      "vol": 3,
      "name": "Dreamcore",
      "cn": "梦核",
      "tone": "dreamcore",
      "summary": "Fog, soft light, landscapes that feel remembered rather than seen.",
      "cn_summary": "雾、柔光、那些像被想起而非被看见的风景。",
      "sref": "5184362986",
      "prompt": "dreamcore landscape, fog, soft light, --ar 3:2 --sref 5184362986 --v 7",
      "use": "梦境 · 童年记忆 · 柔和色 · 概念艺术",
      "palette": [
        "#3a2a4a",
        "#6a4a7a",
        "#a06aa0",
        "#d8a0c8",
        "#f8e0e8"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "samurai",
      "vol": 3,
      "name": "Samurai",
      "cn": "武士",
      "tone": "samurai",
      "summary": "A bowl of ramen is a story. Bushido as visual philosophy.",
      "cn_summary": "一碗拉面就是一个故事。武土道作为视觉哲学。",
      "sref": "5672452819",
      "prompt": "closeup of steaming ramen, robotic arm, tatami, --ar 16:9 --sref 5672452819 --v 7",
      "use": "武士 · 静物 · 暖色 · 编辑",
      "palette": [
        "#0a0a0a",
        "#2a0a0a",
        "#6a1a1a",
        "#c8302a",
        "#f0d8a0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "mechalodogrom",
      "vol": 3,
      "name": "Mechalodogrom",
      "cn": "机甲斗技场",
      "tone": "mechalodogrom",
      "summary": "Giant machines. Cybernetics. The eternal promise of robots.",
      "cn_summary": "巨型机械。控制论。机器人永恒的承诺。",
      "sref": "5836209894",
      "prompt": "giant mech in colosseum arena, dust, --ar 3:2 --exp 100 --sref 5836209894 --v 7",
      "use": "机甲 · 战斗场景 · 概念艺术 · 海报",
      "palette": [
        "#0a0e1a",
        "#1a2a3a",
        "#3a5a7a",
        "#4080d4",
        "#a0c8f0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "balloon",
      "vol": 3,
      "name": "Balloon",
      "cn": "气球",
      "tone": "balloon",
      "summary": "Inflatable textures. Softness as its own kind of strength.",
      "cn_summary": "充气质感。柔软，作为它自己的一种力量。",
      "sref": "6179566788",
      "prompt": "a city made of pastel balloons, soft light, --ar 16:9 --sref 6179566788 --v 7",
      "use": "柔软 · 治愈 · 玩具感 · 杂志",
      "palette": [
        "#3a2a3a",
        "#7a4a6a",
        "#c87898",
        "#f4a8c0",
        "#fce0e8"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "kultur",
      "vol": 3,
      "name": "Kultur",
      "cn": "文化",
      "tone": "kultur",
      "summary": "Crown shyness and mosh pits. Spectral presence of cultural memory.",
      "cn_summary": "树冠羞避与狂躁的金属区。文化记忆的幽光在场。",
      "sref": "6519358186",
      "prompt": "crown shyness in dense forest, ghostly figures, --ar 2:3 --sref 6519358186 --v 7",
      "use": "自然 · 神秘 · 黑金属 · 杂志",
      "palette": [
        "#0a0a0a",
        "#2a2a2a",
        "#5a5a5a",
        "#8a8a8a",
        "#d0d0d0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "id": "camera-obscura",
      "vol": 3,
      "name": "Camera Obscura",
      "cn": "暗箱",
      "tone": "camera-obscura",
      "summary": "Black and white. Medieval armor. Light against dark. The Knight.",
      "cn_summary": "黑白。中世纪盔甲。光对暗。骑士。",
      "sref": "5770255736",
      "prompt": "medieval knight in black armor, high contrast b&w, --ar 16:9 --sref 5770255736 --v 7",
      "use": "黑白 · 摄影 · 戏剧 · 编辑",
      "palette": [
        "#000000",
        "#1a1a1a",
        "#3a3a3a",
        "#7a7a7a",
        "#f0f0f0"
      ],
      "updated_at": "2026-06-09T13:22:12"
    }
  ],
  "FUNDAMENTALS": [
    {
      "id": "thesis",
      "tier": "Foundation",
      "num": 1,
      "code": "F·01",
      "name": "Thesis",
      "cn": "主张",
      "summary": "The singular idea that governs the world. Not a theme, not a vibe — a position.",
      "cn_summary": "统治这个世界的\"单一主张\"。不是主题、不是氛围——而是一个立场。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "基础"
    },
    {
      "id": "lore",
      "tier": "Foundation",
      "num": 2,
      "code": "F·02",
      "name": "Lore",
      "cn": "隐藏历史",
      "summary": "The invisible history that gives weight to everything the viewer sees.",
      "cn_summary": "赋予观者所见一切以重量的\"看不见的历史\"。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "基础"
    },
    {
      "id": "archetype-fund",
      "tier": "Foundation",
      "num": 3,
      "code": "F·03",
      "name": "Archetypes",
      "cn": "原型",
      "summary": "Recurring figures and symbols. Not characters but patterns of meaning.",
      "cn_summary": "反复出现的形象与符号。不是角色，而是意义的图案。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "基础"
    },
    {
      "id": "visual-language",
      "tier": "Craft",
      "num": 4,
      "code": "C·04",
      "name": "Visual Language",
      "cn": "视觉语言",
      "summary": "Systematic choices in color, material, light, texture, form that make the world recognizable.",
      "cn_summary": "颜色、材质、光线、纹理、形态上的系统性选择，让世界在任意一张图上都能被识别。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "技艺"
    },
    {
      "id": "composition",
      "tier": "Craft",
      "num": 5,
      "code": "C·05",
      "name": "Composition",
      "cn": "构图",
      "summary": "How you direct the eye within a single frame, creating hierarchy and emotional weight.",
      "cn_summary": "在单帧之内引导眼睛的方式——它创造层次与情绪重量。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "技艺"
    },
    {
      "id": "tone",
      "tier": "Craft",
      "num": 6,
      "code": "C·06",
      "name": "Tone",
      "cn": "语调",
      "summary": "The emotional register of the world. Not a mood board — the consistent feeling that persists.",
      "cn_summary": "世界的情感寄存器。不是情绪板——是贯穿每一件作品的稳定感觉。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "技艺"
    },
    {
      "id": "atmosphere",
      "tier": "Craft",
      "num": 7,
      "code": "C·07",
      "name": "Atmosphere",
      "cn": "氛围",
      "summary": "The environmental layer — the breath of the world. Light, depth, weather, air quality.",
      "cn_summary": "环境层——世界的呼吸。光线、纵深、天气、空气质感。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "技艺"
    },
    {
      "id": "scale",
      "tier": "Craft",
      "num": 8,
      "code": "C·08",
      "name": "Scale",
      "cn": "尺度",
      "summary": "The relationship between the subject and the environment. How big things feel.",
      "cn_summary": "主体与环境之间的关系——东西有多大、人物在建筑前显得多小。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "技艺"
    },
    {
      "id": "story",
      "tier": "Direction",
      "num": 9,
      "code": "D·09",
      "name": "Story",
      "cn": "故事",
      "summary": "Implied movement within a world. What happened before the frame, what is about to happen after.",
      "cn_summary": "世界内部被暗示的运动——这一帧之前发生了什么、之后即将发生什么。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "方向"
    },
    {
      "id": "pacing",
      "tier": "Direction",
      "num": 10,
      "code": "D·10",
      "name": "Pacing",
      "cn": "节奏",
      "summary": "The rhythm of revelation. What you show first, what you withhold.",
      "cn_summary": "揭示的节奏——先展示什么、保留什么、张力如何在序列中累积。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "方向"
    },
    {
      "id": "editing",
      "tier": "Direction",
      "num": 11,
      "code": "D·11",
      "name": "Editing",
      "cn": "剪辑",
      "summary": "The discipline of coherence — the decision of what stays and what goes.",
      "cn_summary": "连贯性的纪律——什么留、什么走。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "方向"
    },
    {
      "id": "repetition-variation",
      "tier": "Direction",
      "num": 12,
      "code": "D·12",
      "name": "Repetition & Variation",
      "cn": "重复与变化",
      "summary": "How motifs recur with enough consistency to feel intentional and enough difference to feel alive.",
      "cn_summary": "母题以\"足够一致显得有意、又足够不同显得鲜活\"的方式重现。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "方向"
    },
    {
      "id": "signature",
      "tier": "Direction",
      "num": 13,
      "code": "D·13",
      "name": "Signature",
      "cn": "签名",
      "summary": "What makes your worlds recognizable. Your fingerprint across all 14 principles.",
      "cn_summary": "让你的世界被认出的东西——14 条原理协同产生的指纹。",
      "body": "",
      "cn_body": "",
      "updated_at": "2026-06-09T13:22:12",
      "tierCn": "方向"
    }
  ],
  "LOGS": [
    {
      "slug": "log-001",
      "num": "001",
      "title": "Stop Rendering Prompts. Start Building Worlds.",
      "cn": "别再渲染提示词，开始构建世界。",
      "date": "2024-08-12",
      "tag": "Foundation",
      "summary": "Why most AI image creators stay at the surface, and the structural shift that takes you from prompts to worlds.",
      "cn_summary": "为什么大多数 AI 图像创作者停留在表面，从提示词到世界的那一次结构跃迁是什么。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-002",
      "num": "002",
      "title": "The Consistency Crisis",
      "cn": "一致性危机",
      "date": "2024-09-04",
      "tag": "Craft",
      "summary": "Diagnosing why a 100-output series starts to fall apart, and the three fixes that hold it together.",
      "cn_summary": "诊断一个 100 张输出系列为何会逐渐散架，以及把它兜住的三种修法。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-003",
      "num": "003",
      "title": "Engineering Attention With The Kinetic Workflow",
      "cn": "用动量工作流工程化注意力",
      "date": "2024-09-22",
      "tag": "Direction",
      "summary": "A workflow that rewards momentum, not perfection. The opposite of endless tweaking.",
      "cn_summary": "一种奖励\"动量\"而非\"完美\"的工作流，是无尽微调的反面。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-004",
      "num": "004",
      "title": "The Antidote to the Blank Canvas",
      "cn": "对抗空白画布的解药",
      "date": "2024-10-10",
      "tag": "Foundation",
      "summary": "How to never start from zero. The 7-day warm-up that pre-loads a world.",
      "cn_summary": "如何永不从零开始。预热一个世界的 7 天流程。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-005",
      "num": "005",
      "title": "The Path of Mastery",
      "cn": "精通之路",
      "date": "2024-10-30",
      "tag": "Craft",
      "summary": "The four stages of world-builder maturity, and why most stop at stage 2.",
      "cn_summary": "世界构建者的四个成熟阶段，以及为什么大多数人停在第二阶段。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-008",
      "num": "008",
      "title": "The Architecture of Hallucinations: Deconstructing Codex Vol. II",
      "cn": "幻觉的建筑学：解构法典第二卷",
      "date": "2024-12-15",
      "tag": "Volume 2",
      "summary": "A behind-the-scenes walkthrough of how Volume 2 was built, and what got cut.",
      "cn_summary": "第二卷是如何被构建的幕后拆解，以及被砍掉的部分。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-011",
      "num": "011",
      "title": "In 2026, Decision-Making Is the Only Skill That Can't Be Outsourced",
      "cn": "2026 年，唯一无法被外包的技能是决策",
      "date": "2025-01-20",
      "tag": "Direction",
      "summary": "The Director's Moment. Why curation is the moat in an age of infinite generation.",
      "cn_summary": "导演的时刻。在生成无限的时代，策展才是护城河。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    },
    {
      "slug": "log-016",
      "num": "016",
      "title": "30 Worlds Launch",
      "cn": "30 个世界发布",
      "date": "2025-03-12",
      "tag": "Volume 3",
      "summary": "Notes on shipping 30 fully realized worlds in a single drop.",
      "cn_summary": "一口气发布 30 个完整世界时的笔记。",
      "body": "",
      "updated_at": "2026-06-09T13:22:12"
    }
  ],
  "_generated_at": "2026-06-09T13:23:35"
};
